DATASET:
  project_dir: './'
  data_dir: 'data'
  loading_data: 'LOAD_LABEL_UNLABEL' # ----LOAD_ORIGINAL'--- 'LOAD_LABEL_UNLABEL' ---
  dataset: 'CIFAR10'
  strongaugment: 'RA'
  label_num: 4000
  num_expand_x: 65536 # total number of labeled samples
  mu: 7
  batch_size: 64
  num_workers: 4
  batch_balanced: False

MODEL:
  name: 'WideResNet_Lk'             #---- 'WideResNet'---'WideResNet_Lk'-------
  depth: 28
  widen_factor: 2
  num_classes: 10
  dropout: 0.0

EXPERIMENT:
  name: 'FMExperiment'              #---- 'VANILLA'--- 'FMExperiment' ---
  out_model: './checkpoints/'
  log_path: './outputs/exp1'
  used_gpu: True

  optim_lr: 0.03
  optim_momentum: 0.9
  used_nesterov: True
  warmup: 0

  ema_used: True
  ema_decay: 0.999

  threshold: 0.95
  lambda_unlabeled: 1

  batch_size: 64
  n_imgs_per_epoch: 65536
  epoch_n: 1024
  save_every: 500

  resume: False
  resume_checkpoints: './checkpoints/exp1/FMExperiment_epoch_0.pth.tar'

  save_cfmatrix: True
  batch_balanced: True 

Logging:
  name: "FM"
  seed: 1265                    #---- None ---
