DATASET:
  project_dir: './'
  data_dir: 'data'
  dataset: 'CIFAR10'
  strongaugment: 'RA'  #'CTA'
  label_num: 4000
  num_expand_x: 65536 # total number of labeled samples
  mu: 7
  batch_size: 64
  num_workers: 4

MODEL:
  name: 'WideResnet'
  depth: 28
  widen_factor: 2
  num_classes: 10
  dropout: 0.0

EXPERIMENT:
  name: 'FMTrainer'
  out_model: './checkpoints/'
  log_path: './outputs/exp1'
  used_gpu: True

  optim_lr: 0.03
  optim_momentum: 0.9
  used_nesterov: True

  batch_size: 64
  epoch_n: 1024
  save_every: 50

  resume: False
  resume_checkpoints: './checkpoints/xx.pth'

Logging:
  name: "FM"
  seed: 1265